config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :dogs, only: %i[show index new create edit update] do
    post '/post_like', action: :post_like, as: :post_like, on: :member
  end

  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many_attached :images
  has_many :likes
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates_presence_of :dog_id, :user_id
  belongs_to :dog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dogs, foreign_key: :owner_id
  has_many :likes, foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :denied
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :post_like]
  before_action :check_owner, only: [:edit, :update, :destroy]

  MAX_ITEMS_PER_PAGE = 5

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog
      .includes(:likes)
      .order('likes.created_at desc')
      .page(current_page)
      .per(MAX_ITEMS_PER_PAGE)
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params.to_h.merge({ owner_id: current_user.id }))

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  def post_like
    if current_user_the_owner?
      redirect_to root_path
      return
    end

    like = Like.new(dog_id: @dog.id, user_id: current_user.id)
    respond_to do |format|
      if like.save
        format.html { redirect_to @dog, notice: 'Dog was liked successfully!' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :description, :images)
  end

  def current_page
    @current_page ||= pagination_params[:page].nil? ? 1 : pagination_params[:page]
  end

  # introduced params used for pagination
  def pagination_params
    params.permit(:page)
  end

  def post_like_params
    params.permit(:dog_id)
  end

  def current_user_the_owner?
    @current_user_the_owner ||= current_user.id == @dog.owner_id
  end

  def check_owner
    if !current_user_the_owner?
      flash[:denied] = "Access denied as you don't own #{@dog.name}"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
  def current_user_the_owner?(dog_owner_id)
    return false if current_user.nil?
    @current_user_the_owner ||= current_user.id == dog_owner_id
  end
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :image, as: :file, input_html: { multiple: true } %>

  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<article>
  <a href="<%= url_for(dog) %>">
    <h2 class="dog-name"><%= dog.name %></h2>
  </a>
  <% if !current_user_the_owner?(dog.id) and !current_user.nil? %>
    <%= form_with(model: dog, url: post_like_dog_url(dog), method: :post, html: { name: 'dog_like_form' }) do |f| %>
      <%= submit_tag('Like!') %>
    <% end %>
  <% end %>
  <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
</article>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<% @dogs.each_with_index do |dog, index| %>
  <%= render partial: 'thumbnail', locals: {dog: dog} %>
  <% if ((index + 1) % 2) == 0 %>
    <%= image_tag 'ad.jpg' %>
  <% end %>
<% end %>
<%= paginate @dogs %>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>

  <% @dog.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>

  <p><%= @dog.description %></p>
  <% if current_user_the_owner?(@dog.owner_id) %>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>
      <header>
        <h1><%= link_to 'Dog Profile Demo', root_path %></h1>
        <div class="actions">
          <% if current_user %>
            <%= link_to 'Add your dog', new_dog_path %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>

  </body>
</html>